-- Active: 1773422227617@@127.0.0.1@3306
CREATE TABLE area(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    Setor TEXT NOT NULL,
    Formacao TEXT NOT NULL,
    Admissao TEXT NOT NULL,
    Salario INTEGER NOT NULL
);